create database retail_project;

use retail_project;

DROP TABLE retail_sales;

CREATE TABLE retail_sales (
InvoiceNo VARCHAR(20),
StockCode VARCHAR(20),
Description TEXT,
Quantity INT,
InvoiceDate DATETIME,
UnitPrice FLOAT,
CustomerID FLOAT,
Country VARCHAR(50),
Revenue FLOAT
);

SET GLOBAL local_infile = 1;

SHOW VARIABLES LIKE 'local_infile';

SHOW VARIABLES LIKE 'secure_file_priv';

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/cleaned_retail_data.csv'
INTO TABLE retail_sales
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT COUNT(*) FROM retail_sales;

-- Q1. What is the total revenue generated by the company?
select round(sum(Revenue),3) as total_revenue
from retail_sales;

-- Q2. How many total orders were placed?
SELECT COUNT(DISTINCT InvoiceNo) AS total_orders
FROM retail_sales;

-- Q3. How many unique customers made purchases?
select count(distinct CustomerID) as total_customers
from retail_sales;

-- Q4. What is the average order value?
SELECT ROUND(SUM(Revenue) / COUNT(DISTINCT InvoiceNo),2) AS avg_order_value
FROM retail_sales;

-- Q5. What are the top 10 best-selling products by quantity?
SELECT Description, SUM(Quantity) AS total_quantity
FROM retail_sales
GROUP BY Description
ORDER BY total_quantity DESC
LIMIT 10;

-- Q6. Which products generate the highest revenue?
select Description, round(SUM(Revenue),2) AS highest_revenue
from retail_sales
GROUP BY Description
ORDER BY highest_revenue DESC
limit 1;

-- Q7. Which products sell the least?
select Description, sum(Quantity) as least_quantity
from retail_sales
group by Description
order by least_quantity ASC
limit 10;

-- Q8. Who are the top 10 customers by total spending?
select CustomerID, round(sum(Revenue),2) as total_spent
from retail_sales
group by CustomerID
order by total_spent DESC
limit 10;

-- Q9. How many orders does each customer place on average?
SELECT ROUND(COUNT(DISTINCT InvoiceNo) / COUNT(DISTINCT CustomerID),2)
AS avg_orders_per_customer
FROM retail_sales;


-- Q10. Which customers generate the most revenue?
select CustomerID, round(SUM(Revenue),2) AS revenue
from retail_sales
GROUP BY CustomerID
ORDER BY revenue DESC
limit 5;

-- Q11. Which countries generate the highest revenue?
select Country, round(SUM(Revenue),2) AS revenue
from retail_sales
GROUP BY Country
ORDER BY revenue DESC
limit 5;

-- Q12. Which countries have the most customers?
SELECT Country,
COUNT(DISTINCT CustomerID) AS total_customers
FROM retail_sales
GROUP BY Country
ORDER BY total_customers DESC;


-- Q13. How does revenue change over time?
SELECT
YEAR(InvoiceDate) AS year,
MONTH(InvoiceDate) AS month,
ROUND(SUM(Revenue),2) AS monthly_sales
FROM retail_sales
GROUP BY year, month
ORDER BY year, month;

-- Q14. Which month has the highest sales?
SELECT
MONTH(InvoiceDate) AS month,
ROUND(SUM(Revenue),2) AS total_sales
FROM retail_sales
GROUP BY month
ORDER BY total_sales DESC
LIMIT 1;

-- Q15. Which day of the week has the most orders?
SELECT
DAYNAME(InvoiceDate) AS day,
COUNT(DISTINCT InvoiceNo) AS total_orders
FROM retail_sales
GROUP BY day
ORDER BY total_orders DESC;







